---
- name: Add Elastic Apt Key
  apt_key: keyserver=pgp.mit.edu id=D88E42B4

- name: Add Elastic Repo
  apt_repository:
    repo='deb http://packages.elastic.co/kibana/{{ kibana_repo_version }}/debian stable main'
    state=present

- name: Install Kibana
  apt: name=kibana update_cache=yes cache_valid_time=3600 state=present

- name: Configure Kibana
  template:
    src=kibana-{{ kibana_repo_version }}.yml.j2
    dest=/opt/kibana/config/kibana.yml
    owner=root
    group=root
    mode=0644
  notify:
    - Restart Kibana

- name: Start and Enable Kibana Service
  service: name=kibana state=running enabled=yes

