---
- name: download kibana binary tarball
  get_url:
      url: "https://download.elastic.co/kibana/kibana/kibana-{{ kibana_version }}.tar.gz"
      dest: "/var/tmp/kibana-{{ kibana_version }}.tar.gz"


- name: create kibana dir
  file: path={{ kibana_root }} state=directory

- name: Expand Kibana
  command: "tar -xz --strip-components=1 -C {{ kibana_root }} -f /var/tmp/kibana-{{ kibana_version }}.tar.gz"
  args:
    creates: "{{ kibana_root }}/src/bin/kibana.js"

- name: kibana default
  copy: src=kibana.default dest=/etc/default/kibana owner=root group=root mode=0644

- name: kibana init.d script
  copy: src=kibana.initd dest=/etc/init.d/kibana owner=root group=root mode=0755

- name: create kibana system user
  user: name=kibana system=yes

- name: Configure Kibana
  template:
    src=kibana-{{ kibana_major }}.yml.j2
    dest="{{ kibana_root }}/config/kibana.yml"
    owner=root
    group=root
    mode=0644
  notify:
    - Restart Kibana

- name: Start and Enable Kibana Service
  service: name=kibana state=running enabled=yes

